apiVersion: v2
name: aws-ebs-csi-driver
description: A Helm chart for the AWS EBS CSI Driver.
version: 4.1.1
appVersion: 1.51.0
home: https://github.com/giantswarm/aws-ebs-csi-driver-app
icon: https://s.giantswarm.io/app-icons/aws/2/dark.svg
annotations:
  application.giantswarm.io/team: phoenix
