apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aws-ebs-csi-controller
  namespace: kube-system
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name |Â quote }}
  policyTypes:
  - Egress
