apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterID }}-aws-ebs-csi-driver-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ebs-csi-driver-app-bundle.labels" $ | nindent 4 }}
data:
  values: |
  {{- include "giantswarm.setValues" . -}}
  {{- (tpl (.Values | toYaml | toString) $) | nindent 4 }}
